### PR TITLE
Updated combo_merge

### PR DESCRIPTION
**Pull request by i6c**
i accidentally made a spelling mistake, line 561

this is just a concept for you ColderVoid

### CODE REVIEW

**Comment by i6c** [comment]
I dont know if you are active anymore, BTW

**Comment by ColderVoid** [comment]
I think it's a good start. I just need to add file selection via GUI and the ability to merge multiple files (;. And yes I'm active from time to time.

**Comment by i6c** [comment]
you can use tkinter

`path = filedialog.openfilenames()
for filename in path:`
then whatever code

**Comment by ColderVoid** [comment]
I have function for that called "file_select" in line 78 (;

**Pull request merged**
